# -*- coding: utf-8 -*-
# @Time    : 2026/7/24 18:20
# @Author  : D.N. Huang
# @Email   : CarlCypress@yeah.net
# @FileName: plot_kmeans_internal_metrics.py
# @Project : Causal3D-Net
import os, argparse

import matplotlib.pyplot as plt
import pandas as pd


METRIC_SETTINGS = [
    ("davies_bouldin_index", "Davies-Bouldin Index", "min"),
    ("silhouette_score", "Silhouette Score", "max"),
    ("calinski_harabasz_index", "Calinski-Harabasz Index", "max"),
    ("inertia", "Inertia / WCSS", "elbow"),
    ("dunn_index", "Dunn Index", "max"),
    ("gap_statistic", "Gap Statistic", "max"),
    ("s_dbw_index", "S_Dbw Index", "min"),
]


def annotate_best(ax, scores, metric_name, direction):
    if direction == "elbow":
        return

    if direction == "min":
        best_index = scores[metric_name].idxmin()
    else:
        best_index = scores[metric_name].idxmax()

    best_k = int(scores.loc[best_index, "k"])
    best_score = float(scores.loc[best_index, metric_name])
    ax.scatter(
        [best_k],
        [best_score],
        color="#D1495B",
        edgecolor="white",
        linewidth=0.8,
        s=65,
        zorder=3,
    )
    ax.annotate(
        f"k={best_k}",
        xy=(best_k, best_score),
        xytext=(7, 10),
        textcoords="offset points",
        fontsize=8,
        color="#A51C30",
    )


def plot_internal_metrics(score_csv, output_path, dpi=300):
    if not os.path.isfile(score_csv):
        raise FileNotFoundError(
            f"Metric CSV not found: {score_csv}\n"
            "Run `python -m src.utils.kmeans_internal_metrics` first."
        )

    scores = pd.read_csv(score_csv)
    required_columns = {"k"}.union({
        metric_name for metric_name, _, _ in METRIC_SETTINGS
    })
    missing_columns = required_columns.difference(scores.columns)
    if missing_columns:
        raise ValueError(
            f"Metric CSV is missing required columns: {sorted(missing_columns)}"
        )
    if scores.empty:
        raise ValueError("Metric CSV contains no rows.")

    scores = scores.sort_values("k").reset_index(drop=True)
    fig, axes = plt.subplots(2, 4, figsize=(16, 8.5))
    axes = axes.ravel()

    for ax, (metric_name, title, direction) in zip(axes, METRIC_SETTINGS):
        if metric_name == "gap_statistic" and "gap_standard_error" in scores:
            ax.errorbar(
                scores["k"],
                scores[metric_name],
                yerr=scores["gap_standard_error"],
                color="#276FBF",
                marker="o",
                markersize=5,
                linewidth=1.8,
                capsize=3,
            )
        else:
            ax.plot(
                scores["k"],
                scores[metric_name],
                color="#276FBF",
                marker="o",
                markersize=5,
                linewidth=1.8,
            )

        annotate_best(ax, scores, metric_name, direction)
        direction_text = {
            "min": "lower is better",
            "max": "higher is better",
            "elbow": "select the elbow",
        }[direction]
        ax.set_title(f"{title}\n({direction_text})", fontsize=11)
        ax.set_xlabel("Number of clusters (k)")
        ax.set_ylabel(title)
        ax.set_xticks(scores["k"].astype(int))
        ax.grid(axis="y", linestyle="--", alpha=0.35)

    size_ax = axes[-1]
    size_ax.plot(
        scores["k"],
        scores["smallest_cluster_size"],
        color="#D1495B",
        marker="o",
        linewidth=1.8,
        label="Smallest cluster",
    )
    size_ax.plot(
        scores["k"],
        scores["largest_cluster_size"],
        color="#2A9D8F",
        marker="o",
        linewidth=1.8,
        label="Largest cluster",
    )
    size_ax.set_title("Cluster Size Balance", fontsize=11)
    size_ax.set_xlabel("Number of clusters (k)")
    size_ax.set_ylabel("Number of samples")
    size_ax.set_xticks(scores["k"].astype(int))
    size_ax.grid(axis="y", linestyle="--", alpha=0.35)
    size_ax.legend(frameon=False, fontsize=8)

    fig.suptitle(
        "Internal Evaluation of K-Means on Radiomics Features",
        fontsize=15,
        y=1.01,
    )
    fig.tight_layout()
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)

    print(f"Figure saved to {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Visualize internal K-Means validity indices."
    )
    parser.add_argument(
        "--score_csv",
        type=str,
        default="/home/huangdn/Causal3D-Net/src/logging_record/"
                "kmeans_internal_metrics.csv",
        help="Metric CSV generated by kmeans_internal_metrics.py.",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="/home/huangdn/Causal3D-Net/src/logging_record/"
                "kmeans_internal_metrics.png",
        help="Path to save the internal-metric figure.",
    )
    parser.add_argument("--dpi", type=int, default=600)
    args = parser.parse_args()

    plot_internal_metrics(
        score_csv=args.score_csv,
        output_path=args.output,
        dpi=args.dpi,
    )
